### ISSUE TITLE
Editor not working and desktop is active

### ISSUE THREAD

**Issue by papampi** [domferr/tilingshell#29]
Ubuntu 24.04, tilling shell version 7
When go to editor desktop is active and not the editor.
Clicking in editor areas clicks on desktop and even open desktop shortcuts

Edit:
Manually installed v8 and same issue

**Comment by domferr** [comment]
Hi @papampi thank you for opening this issue. Are you able to share how to reproduce the problem?

**Comment by papampi** [comment]
> Hi @papampi thank you for opening this issue. Are you able to share how to reproduce the problem?

Hi, 
And thanks for this awesome tilling shell
Just open editor and tried to edit:

https://github.com/domferr/tilingshell/assets/1108483/66236cbf-ef50-4f56-9c7c-ba334032fdec


Just added what I needed with export > edit > import.

**Comment by papampi** [comment]
It seems like ubuntu default "Desktop icons NG (DING)" has conflict with it, disabled it and its working.

**Comment by domferr** [comment]
> disabled it and its working

Thank you for sharing this, it is very useful to understand and fix the problem. It does not happen to me (I use ubuntu as well), so I'm looking into reproduce the problem on my system too so I can fix it.

**Comment by domferr** [comment]
Hi, I leave attached a bugfix, can you confirm it is solved?

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883508/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883512/tilingshell%40ferrarodomenico.com.zip)

**Comment by papampi** [comment]
> Hi, I leave attached a bugfix, can you confirm it is solved?

Hi, unfortunately it's not fixed.
Disabled it, removed folder, copied new one, enabled, logged out, logged in.
Same issue ...
